### ISSUE TITLE
Shader Validation Error with Intel HD Graphics GPU

### ISSUE THREAD

**Issue by plous** [oreonengine/oreon-engine#11]
Question: when I run the application I get the following error:

> apps.oreonworlds.shaders.terrain.TerrainShader Validation Error: Samplers of different types point to the same texture unit

Do I need to update my OpenGL driver or are you using features that my graphics card does not support?

**Comment by oreon3D** [comment]
Do you have ATI or Nvidia card?

**Comment by plous** [comment]
I have an Intel HD Graphics 5500 card

**Comment by oreon3D** [comment]
try to update the driver to latest version, if problem isn't solved post it here and I'll think about it,
The error looks somehow familiar to me...

**Comment by plous** [comment]
I updated to the latest OpenGL drivers. Unfortunately I get the same error. I installed [GLView](http://realtech-vr.com/admin/glview) to generate an OpenGL report. Attached the report. Perhaps it can be of any help. I will try a different computer and tell you the results

[glview-Intel(R) HD Graphics 5500-10.txt](https://github.com/oreon3D/Oreon.Engine-OpenGL-Java/files/1110026/glview-Intel.R.HD.Graphics.5500-10.txt)

**Comment by plous** [comment]
GLview reports some unsupported OpenGL 4.4 features. See screenshot:

![image](https://user-images.githubusercontent.com/29760741/27657315-8f1c35a6-5c4c-11e7-99f0-33d8e4bb9aec.png)

**Comment by plous** [comment]
I missed a part:

![image](https://user-images.githubusercontent.com/29760741/27657424-e759df3e-5c4c-11e7-9558-e4c7410aae2a.png)

These have to do with texture binding.

**Comment by oreon3D** [comment]
The console ouput when the application compiles, the first line shows your GPU's OpenGL version. which is it?

**Comment by plous** [comment]
When I start `apps.oreonworlds.Main` the following is displayed in the console:
> OpenGL version: 4.3.0 - Build 10.18.10.3995
> Max Geometry Uniform Blocks: 35372
> Max Geometry Shader Invocations: 36442
> Max Uniform Buffer Bindings: 35375
> Max Uniform Block Size: 35376
> Wed Jun 28 21:41:30 CEST 2017 INFO:Use Java PNG Loader = true
> apps.oreonworlds.shaders.terrain.TerrainShader Validation Error: Samplers of different types point to the same texture unit Validation Error: Samplers of different types point to the same texture unit

**Comment by oreon3D** [comment]
ok 4.3 is enough, I'll inform you tomorrow

**Comment by plous** [comment]
`uniform sampler2DArray shadowMaps` in Terrain_FS.glsl is causing the error. When I change the code so this uniform is not used, the shaders compile. The program starts loading and compiling the other shaders. Unfortunately this causes errors in other shaders (uniforms not found).

**Comment by oreon3D** [comment]
Yes the uniforms are not found because glsl does an optimization when it's compiling the shader and removes unused uniforms, so it won't be found. But anyways, the sampler2DArray is necessary for shadows, I have an idea, I send you the solution for this issue soon

 

Gesendet: Samstag, 01. Juli 2017 um 00:14 Uhr
Von: plous <notifications@github.com>
An: "oreon3D/Oreon.Engine-OpenGL-Java" <Oreon.Engine-OpenGL-Java@noreply.github.com>
Cc: Fynn <fynnfluegge@gmx.de>, Comment <comment@noreply.github.com>
Betreff: Re: [oreon3D/Oreon.Engine-OpenGL-Java] Shader Validation Error (#11)


uniform sampler2DArray shadowMaps in Terrain_FS.glsl is causing the error. When I change the code so this uniform is not used, the shaders compile. The program starts loading and compiling the other shaders. Unfortunately this causes errors in other shaders (uniforms not found).
