### ISSUE TITLE
Spring usage

### ISSUE THREAD

**Issue by RubenWalraevens** [oreonengine/oreon-engine#31]
Hello

First of all. Wonderful engine, keep up the good work!

I am currently wondering why you are using Spring in your project. As far as I searched into the source code of Oreon I see only one reason.. Dependency Injection. Why did you choose dependency injection over just creating an instance and passing it around?

Thank you.

Ruben

**Comment by oreonengine** [comment]
Hi, thank you! I used it for creating Context objects (OpenGL and Vulkan), is that what you mean?

**Comment by RubenWalraevens** [comment]
As far as I know DI has an impact on the performance/memory usage because you need to keep the references and lookup time etc.
Here at work we use for certain batch operations no dependency injection because it would take up too much resources. So I would think that for a game engine it is more or less the same.

Just a random thought of mine. Please correct me if I am wrong on this one.

**Comment by oreonengine** [comment]
hm you are maybe right, I don't really know, to be on the safe side I think I will remove spring injection soon

**Comment by RubenWalraevens** [comment]
While I did a quick search I saw that it depends on many factors. One of them is for example at which stage of application you use your DI. In your case I believe it is at startup. So it won't have that much of an influence on the game performance. However, it does not feel right in a game engine. That is purely my opinion. If you feel like it's doing his job like it should and you don't see a drawback of any kind. Keep it :)

**Comment by oreonengine** [comment]
Alright, anyways thanks for your remarks :)

**Comment by aromanelli** [comment]
@oreonengine DI is dependent on reflection, which is a performance hog in the old days.  Nowadays, computers can overcome that performance hurdle, but its still there, and for gaming/video, which is different than business apps, I'd too also suggest moving away from Spring and DI, for performance reasons.  Having said that, if a pro-Spring person just read what I wrote, they'd probably drive over to my house and burn it down! :p  But usually the less frameworks/libraries you use, the better, and reflection on its own needs more cpu than non-reflection code.

**Comment by oreonengine** [comment]
Alright ;) I will do some rework on engine context and remove spring soon

**Comment by aromanelli** [comment]
@ThomasKasene Right now this project (seems to be to me) is a front-end graphics application.  I'd totally agree that if you were using server/back-end side logic then using something like Spring would work well.  But even then, you'd use that library only on the modules that deal with back-end infrastructure.

Its been my understanding that for graphics intensive applications you tend to try to get "the rubber as close to the road" as possible, performance wise, hence my original recommendation.  In the past, Java would not even be considered for an app like this, because only c++ could give that kind of performance.  Now that Java is right up there with c++, that's a different story, but the focus has always been on performance, squeezing out as much FPS as you can.

As a general rule its always good to remove libraries/code that are used little or not at all, if possible, to remove bloat whenever possible.Having said that, if library functionality is used well/often, then its no longer bloat, but a necessary library, and should be used.

**Comment by ThomasKasene** [comment]
Of course - I'm all for not dragging in frameworks that aren't necessary, my point was just to make sure you integrate them for the right reasons :) 

Spring comes with some other features that the application could use as well, like an event system. Such things can of course be custom made from scratch, so it's a matter of deciding how much of such boilderplate code you want to have to maintain yourself.
